- name: "Deploy FRR {{ frr_version }} on {{ ansible_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  yum:
    name: https://github.com/FRRouting/frr/releases/download/frr-6.0.2/frr-6.0.2-01.el7.centos.x86_64.rpm
    state: present

- name: "Create a FRR service account on {{ ansible_hostname }}"
  user:
    name: "{{ service_account_name }}"
    password: "{{ service_account_password }}"
    groups: 
      - frrvty
    append: yes
    shell: /bin/vtysh
    update_password: always
  when: frr_create_service_account|bool  
  
- name: "Enable specified protocol daemons - default is zebra"
  lineinfile:
    path: /etc/frr/daemons
    regexp: '^{{ item }}='
    line: '{{ item }}=yes'
    owner: root
    group: root
    mode: 0644
  loop: "{{ frr_enable_daemons }}"
  notify:
    - restart_frr_service






