- name: "Remove FRR from {{ ansible_hostname }}"
  yum:
    name: frr
    state: absent
  register: result

- name: "Remove service account from {{ ansible_hostname }}"
  user:
    name: "{{ service_account_name }}"
    state: absent
    remove: yes
  when: frr_remove_service_account|bool
