---
# tasks file for ansible-network.frr
#
- name: initialize function
  include_tasks: includes/init.yaml

- name: set role supported functions
  set_fact:
    frr_functions:
      - setup
      - cleanup
      - noop

- name: validate the requested function is supported
  fail:
    msg: "invalid function specified, expected one of {{ frr_functions }}, got {{ function }}"
  when: function | default('noop') not in frr_functions

- name: "validate the argument spec for {{ function }} function"
  validate_role_spec:
    spec: "{{ function }}.yaml"
  when: function is defined and function != 'noop'

- name: include function specific tasks and run
  include_tasks: "{{ function  | default('noop') }}.yaml"
